-- qbegame의 hero, timer데이터 삭제시 저장되는 데이터
TRUNCATE TABLE data_timer RESTART IDENTITY;
TRUNCATE TABLE data_hero RESTART IDENTITY;

-- 로그 데이터
TRUNCATE TABLE log_army RESTART IDENTITY;
TRUNCATE TABLE log_auth RESTART IDENTITY;
TRUNCATE TABLE log_battle RESTART IDENTITY;
TRUNCATE TABLE log_buff RESTART IDENTITY;
TRUNCATE TABLE log_building_administration RESTART IDENTITY;
TRUNCATE TABLE log_building_alliance RESTART IDENTITY;
TRUNCATE TABLE log_building_assign RESTART IDENTITY;
TRUNCATE TABLE log_building_market RESTART IDENTITY;
TRUNCATE TABLE log_building_medical RESTART IDENTITY;
TRUNCATE TABLE log_building_receptionhall RESTART IDENTITY;
TRUNCATE TABLE log_building_storage RESTART IDENTITY;
TRUNCATE TABLE log_building_tradedept RESTART IDENTITY;
TRUNCATE TABLE log_chat RESTART IDENTITY;
TRUNCATE TABLE log_change_name RESTART IDENTITY;
TRUNCATE TABLE log_construction RESTART IDENTITY;
TRUNCATE TABLE log_etc RESTART IDENTITY;
TRUNCATE TABLE log_fortification RESTART IDENTITY;
TRUNCATE TABLE log_friend_gift RESTART IDENTITY;
TRUNCATE TABLE log_hero RESTART IDENTITY;
TRUNCATE TABLE log_hero_combi RESTART IDENTITY;
TRUNCATE TABLE log_hero_command RESTART IDENTITY;
TRUNCATE TABLE log_hero_enchant RESTART IDENTITY;
TRUNCATE TABLE log_hero_encounter RESTART IDENTITY;
TRUNCATE TABLE log_hero_invitation RESTART IDENTITY;
TRUNCATE TABLE log_hero_salary RESTART IDENTITY;
TRUNCATE TABLE log_hero_skill RESTART IDENTITY;
TRUNCATE TABLE log_hero_skill_active RESTART IDENTITY;
TRUNCATE TABLE log_hero_skill_exp RESTART IDENTITY;
TRUNCATE TABLE log_hero_trade RESTART IDENTITY;
TRUNCATE TABLE log_item RESTART IDENTITY;
TRUNCATE TABLE log_occupation_point RESTART IDENTITY;
TRUNCATE TABLE log_point RESTART IDENTITY;
TRUNCATE TABLE log_production RESTART IDENTITY;
TRUNCATE TABLE log_qbig RESTART IDENTITY;
TRUNCATE TABLE log_raid_battle RESTART IDENTITY;
TRUNCATE TABLE log_resource RESTART IDENTITY;
TRUNCATE TABLE log_suppress RESTART IDENTITY;
TRUNCATE TABLE log_technique RESTART IDENTITY;
TRUNCATE TABLE log_temp RESTART IDENTITY;
TRUNCATE TABLE log_territory RESTART IDENTITY;
TRUNCATE TABLE log_troop RESTART IDENTITY;
TRUNCATE TABLE update_history RESTART IDENTITY;

INSERT INTO update_history (note) VALUES('LOG DB INIT');
